package com.hacklab.minecraft.skills.crafting

import com.hacklab.minecraft.skills.skill.SkillType
import org.bukkit.Material

object CraftDifficulty {
    data class CraftInfo(
        val skill: SkillType,
        val difficulty: Int
    )

    private val craftInfoMap: Map<Material, CraftInfo> = buildMap {
        // Blacksmithy - Stone tools (difficulty aligned with stone mining: 5)
        put(Material.STONE_SWORD, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.STONE_AXE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.STONE_PICKAXE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.STONE_SHOVEL, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.STONE_HOE, CraftInfo(SkillType.BLACKSMITHY, 10))

        // Blacksmithy - Iron (difficulty aligned with iron ore mining: 25)
        put(Material.IRON_SWORD, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_AXE, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_PICKAXE, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_SHOVEL, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_HOE, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_HELMET, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_CHESTPLATE, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_LEGGINGS, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.IRON_BOOTS, CraftInfo(SkillType.BLACKSMITHY, 25))

        // Blacksmithy - Gold (slightly easier than iron)
        put(Material.GOLDEN_SWORD, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_AXE, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_PICKAXE, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_SHOVEL, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_HOE, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_HELMET, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_CHESTPLATE, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_LEGGINGS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLDEN_BOOTS, CraftInfo(SkillType.BLACKSMITHY, 20))

        // Blacksmithy - Diamond (difficulty aligned with diamond ore mining: 60 -> 40)
        put(Material.DIAMOND_SWORD, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_AXE, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_PICKAXE, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_SHOVEL, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_HOE, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_HELMET, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_CHESTPLATE, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_LEGGINGS, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.DIAMOND_BOOTS, CraftInfo(SkillType.BLACKSMITHY, 40))

        // Blacksmithy - Netherite (high-end crafting)
        put(Material.NETHERITE_SWORD, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_AXE, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_PICKAXE, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_SHOVEL, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_HOE, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_HELMET, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_CHESTPLATE, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_LEGGINGS, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.NETHERITE_BOOTS, CraftInfo(SkillType.BLACKSMITHY, 60))

        // Blacksmithy - Chain armor
        put(Material.CHAINMAIL_HELMET, CraftInfo(SkillType.BLACKSMITHY, 30))
        put(Material.CHAINMAIL_CHESTPLATE, CraftInfo(SkillType.BLACKSMITHY, 30))
        put(Material.CHAINMAIL_LEGGINGS, CraftInfo(SkillType.BLACKSMITHY, 30))
        put(Material.CHAINMAIL_BOOTS, CraftInfo(SkillType.BLACKSMITHY, 30))

        // Blacksmithy - Other
        put(Material.ANVIL, CraftInfo(SkillType.BLACKSMITHY, 35))
        put(Material.MACE, CraftInfo(SkillType.BLACKSMITHY, 50))

        // Bows and Arrows (now part of Craftsmanship)
        put(Material.BOW, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.CROSSBOW, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.ARROW, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.SPECTRAL_ARROW, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.TIPPED_ARROW, CraftInfo(SkillType.CRAFTSMANSHIP, 25))

        // Craftsmanship - Basic wood items (very easy, entry level)
        put(Material.STICK, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.WOODEN_SWORD, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.WOODEN_AXE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.WOODEN_PICKAXE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.WOODEN_SHOVEL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.WOODEN_HOE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.SHIELD, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.CHEST, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.TRAPPED_CHEST, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BARREL, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.BOOKSHELF, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.CHISELED_BOOKSHELF, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.CRAFTING_TABLE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.LOOM, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.CARTOGRAPHY_TABLE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.FLETCHING_TABLE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.SMITHING_TABLE, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.COMPOSTER, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.LECTERN, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.JUKEBOX, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.NOTE_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.LADDER, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BOWL, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.ITEM_FRAME, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.GLOW_ITEM_FRAME, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.PAINTING, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.ARMOR_STAND, CraftInfo(SkillType.CRAFTSMANSHIP, 15))

        // Craftsmanship - Stairs (all wood types)
        put(Material.OAK_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.SPRUCE_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BIRCH_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.JUNGLE_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.ACACIA_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.DARK_OAK_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.CRIMSON_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.WARPED_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.MANGROVE_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.CHERRY_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BAMBOO_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BAMBOO_MOSAIC_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 5))

        // Craftsmanship - Slabs (all wood types)
        put(Material.OAK_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.SPRUCE_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BIRCH_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.JUNGLE_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.ACACIA_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.DARK_OAK_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CRIMSON_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.WARPED_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.MANGROVE_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CHERRY_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BAMBOO_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BAMBOO_MOSAIC_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 3))

        // Craftsmanship - Doors (all wood types)
        put(Material.OAK_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.SPRUCE_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BIRCH_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.JUNGLE_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.ACACIA_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.DARK_OAK_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CRIMSON_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.WARPED_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.MANGROVE_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CHERRY_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BAMBOO_DOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))

        // Craftsmanship - Trapdoors (all wood types)
        put(Material.OAK_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.SPRUCE_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BIRCH_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.JUNGLE_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.ACACIA_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.DARK_OAK_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CRIMSON_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.WARPED_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.MANGROVE_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CHERRY_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BAMBOO_TRAPDOOR, CraftInfo(SkillType.CRAFTSMANSHIP, 5))

        // Craftsmanship - Fences (all wood types)
        put(Material.OAK_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.SPRUCE_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.BIRCH_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.JUNGLE_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.ACACIA_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.DARK_OAK_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.CRIMSON_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.WARPED_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.MANGROVE_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.CHERRY_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.BAMBOO_FENCE, CraftInfo(SkillType.CRAFTSMANSHIP, 4))

        // Craftsmanship - Fence Gates (all wood types)
        put(Material.OAK_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.SPRUCE_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BIRCH_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.JUNGLE_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.ACACIA_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.DARK_OAK_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CRIMSON_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 7))
        put(Material.WARPED_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 7))
        put(Material.MANGROVE_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CHERRY_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BAMBOO_FENCE_GATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))

        // Craftsmanship - Signs (all wood types)
        put(Material.OAK_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.SPRUCE_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.BIRCH_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.JUNGLE_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.ACACIA_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.DARK_OAK_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.CRIMSON_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.WARPED_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.MANGROVE_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.CHERRY_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))
        put(Material.BAMBOO_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 4))

        // Craftsmanship - Hanging Signs (all wood types)
        put(Material.OAK_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.SPRUCE_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.BIRCH_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.JUNGLE_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.ACACIA_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.DARK_OAK_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.CRIMSON_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.WARPED_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.MANGROVE_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.CHERRY_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))
        put(Material.BAMBOO_HANGING_SIGN, CraftInfo(SkillType.CRAFTSMANSHIP, 6))

        // Craftsmanship - Pressure Plates (wood)
        put(Material.OAK_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.SPRUCE_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BIRCH_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.JUNGLE_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.ACACIA_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.DARK_OAK_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.CRIMSON_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.WARPED_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.MANGROVE_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.CHERRY_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BAMBOO_PRESSURE_PLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))

        // Craftsmanship - Buttons (wood)
        put(Material.OAK_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.SPRUCE_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BIRCH_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.JUNGLE_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.ACACIA_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.DARK_OAK_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CRIMSON_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.WARPED_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.MANGROVE_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CHERRY_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BAMBOO_BUTTON, CraftInfo(SkillType.CRAFTSMANSHIP, 2))

        // Craftsmanship - Boats (all wood types)
        put(Material.OAK_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.SPRUCE_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BIRCH_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.JUNGLE_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.ACACIA_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.DARK_OAK_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.MANGROVE_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.CHERRY_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BAMBOO_RAFT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.OAK_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.SPRUCE_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BIRCH_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.JUNGLE_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.ACACIA_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.DARK_OAK_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.MANGROVE_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.CHERRY_CHEST_BOAT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BAMBOO_CHEST_RAFT, CraftInfo(SkillType.CRAFTSMANSHIP, 12))

        // Craftsmanship - Beds (all colors)
        put(Material.WHITE_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.ORANGE_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.MAGENTA_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.LIGHT_BLUE_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.YELLOW_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.LIME_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.PINK_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.GRAY_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.LIGHT_GRAY_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.CYAN_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.PURPLE_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.BLUE_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.BROWN_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.GREEN_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.RED_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.BLACK_BED, CraftInfo(SkillType.CRAFTSMANSHIP, 8))

        // Craftsmanship - Banners (all colors)
        put(Material.WHITE_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.ORANGE_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.MAGENTA_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIGHT_BLUE_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.YELLOW_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIME_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.PINK_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GRAY_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIGHT_GRAY_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.CYAN_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.PURPLE_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BLUE_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BROWN_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GREEN_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.RED_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BLACK_BANNER, CraftInfo(SkillType.CRAFTSMANSHIP, 10))

        // Craftsmanship - Carpets (all colors)
        put(Material.WHITE_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.ORANGE_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.MAGENTA_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.LIGHT_BLUE_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.YELLOW_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.LIME_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.PINK_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.GRAY_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.LIGHT_GRAY_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CYAN_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.PURPLE_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BLUE_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BROWN_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.GREEN_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.RED_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BLACK_CARPET, CraftInfo(SkillType.CRAFTSMANSHIP, 2))

        // Craftsmanship - Leather
        put(Material.LEATHER_HELMET, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.LEATHER_CHESTPLATE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.LEATHER_LEGGINGS, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.LEATHER_BOOTS, CraftInfo(SkillType.CRAFTSMANSHIP, 15))

        // Craftsmanship - Tools & Gadgets (formerly Tinkering)
        put(Material.SHEARS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.FLINT_AND_STEEL, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.IRON_NUGGET, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.GOLD_NUGGET, CraftInfo(SkillType.CRAFTSMANSHIP, 5))

        // Craftsmanship - Complex items
        put(Material.FISHING_ROD, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.LANTERN, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.SOUL_LANTERN, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.GUNPOWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 20))

        // Craftsmanship - Precision items
        put(Material.CLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 35))
        put(Material.COMPASS, CraftInfo(SkillType.CRAFTSMANSHIP, 35))
        put(Material.SPYGLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 35))
        put(Material.FIREWORK_ROCKET, CraftInfo(SkillType.CRAFTSMANSHIP, 30))

        // Craftsmanship - Mud and Clay (pottery work)
        put(Material.PACKED_MUD, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.MUD_BRICKS, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.MUD_BRICK_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.MUD_BRICK_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.MUD_BRICK_WALL, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.BRICK, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.BRICKS, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.BRICK_SLAB, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.BRICK_STAIRS, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.BRICK_WALL, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.FLOWER_POT, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.DECORATED_POT, CraftInfo(SkillType.CRAFTSMANSHIP, 25))

        // Craftsmanship - Glass items
        put(Material.GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.WHITE_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.ORANGE_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.MAGENTA_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIGHT_BLUE_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.YELLOW_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIME_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.PINK_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GRAY_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIGHT_GRAY_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.CYAN_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.PURPLE_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BLUE_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BROWN_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GREEN_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.RED_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BLACK_STAINED_GLASS_PANE, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GLASS_BOTTLE, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.TINTED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 15))

        // Craftsmanship - Terracotta (glazed)
        put(Material.WHITE_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.ORANGE_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.MAGENTA_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.LIGHT_BLUE_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.YELLOW_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.LIME_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.PINK_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.GRAY_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.LIGHT_GRAY_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.CYAN_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.PURPLE_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.BLUE_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.BROWN_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.GREEN_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.RED_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.BLACK_GLAZED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 20))

        // Craftsmanship - Concrete powder (all colors)
        put(Material.WHITE_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.ORANGE_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.MAGENTA_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.LIGHT_BLUE_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.YELLOW_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.LIME_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.PINK_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.GRAY_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.LIGHT_GRAY_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.CYAN_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.PURPLE_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BLUE_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BROWN_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.GREEN_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.RED_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BLACK_CONCRETE_POWDER, CraftInfo(SkillType.CRAFTSMANSHIP, 12))

        // Craftsmanship - Redstone components (mechanical tinkering)
        put(Material.PISTON, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.STICKY_PISTON, CraftInfo(SkillType.CRAFTSMANSHIP, 28))
        put(Material.DISPENSER, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.DROPPER, CraftInfo(SkillType.CRAFTSMANSHIP, 22))
        put(Material.OBSERVER, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.HOPPER, CraftInfo(SkillType.CRAFTSMANSHIP, 28))
        put(Material.REPEATER, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.COMPARATOR, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.LEVER, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.TRIPWIRE_HOOK, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.DAYLIGHT_DETECTOR, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.TARGET, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.REDSTONE_TORCH, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.REDSTONE_LAMP, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.TNT, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.SCULK_SENSOR, CraftInfo(SkillType.CRAFTSMANSHIP, 40))
        put(Material.CALIBRATED_SCULK_SENSOR, CraftInfo(SkillType.CRAFTSMANSHIP, 45))

        // Craftsmanship - Rails
        put(Material.RAIL, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.POWERED_RAIL, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.DETECTOR_RAIL, CraftInfo(SkillType.CRAFTSMANSHIP, 22))
        put(Material.ACTIVATOR_RAIL, CraftInfo(SkillType.CRAFTSMANSHIP, 22))
        put(Material.MINECART, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.CHEST_MINECART, CraftInfo(SkillType.CRAFTSMANSHIP, 22))
        put(Material.FURNACE_MINECART, CraftInfo(SkillType.CRAFTSMANSHIP, 22))
        put(Material.HOPPER_MINECART, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.TNT_MINECART, CraftInfo(SkillType.CRAFTSMANSHIP, 28))

        // Blacksmithy - Stone building blocks (masonry)
        put(Material.STONE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.STONE_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.STONE_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.STONE_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.CHISELED_STONE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.MOSSY_STONE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.MOSSY_STONE_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.MOSSY_STONE_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.MOSSY_STONE_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.COBBLESTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.COBBLESTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.COBBLESTONE_WALL, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.MOSSY_COBBLESTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.MOSSY_COBBLESTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.MOSSY_COBBLESTONE_WALL, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.SMOOTH_STONE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.SMOOTH_STONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.STONECUTTER, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.FURNACE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.BLAST_FURNACE, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.SMOKER, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GRINDSTONE, CraftInfo(SkillType.BLACKSMITHY, 20))

        // Blacksmithy - Polished stone variants
        put(Material.POLISHED_ANDESITE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.POLISHED_ANDESITE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.POLISHED_ANDESITE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.POLISHED_DIORITE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.POLISHED_DIORITE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.POLISHED_DIORITE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.POLISHED_GRANITE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.POLISHED_GRANITE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.POLISHED_GRANITE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))

        // Blacksmithy - Deepslate variants
        put(Material.POLISHED_DEEPSLATE, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.POLISHED_DEEPSLATE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.POLISHED_DEEPSLATE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.POLISHED_DEEPSLATE_WALL, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.DEEPSLATE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.DEEPSLATE_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.DEEPSLATE_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.DEEPSLATE_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.DEEPSLATE_TILES, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.DEEPSLATE_TILE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.DEEPSLATE_TILE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.DEEPSLATE_TILE_WALL, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.CHISELED_DEEPSLATE, CraftInfo(SkillType.BLACKSMITHY, 25))

        // Blacksmithy - Nether bricks
        put(Material.NETHER_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.NETHER_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.NETHER_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.NETHER_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.NETHER_BRICK_FENCE, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.RED_NETHER_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.RED_NETHER_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.RED_NETHER_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.RED_NETHER_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.CHISELED_NETHER_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 25))

        // Blacksmithy - End stone
        put(Material.END_STONE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.END_STONE_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.END_STONE_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.END_STONE_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 22))

        // Blacksmithy - Quartz
        put(Material.QUARTZ_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.QUARTZ_SLAB, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.QUARTZ_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.QUARTZ_PILLAR, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.CHISELED_QUARTZ_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.QUARTZ_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.SMOOTH_QUARTZ, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.SMOOTH_QUARTZ_SLAB, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.SMOOTH_QUARTZ_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 15))

        // Blacksmithy - Prismarine
        put(Material.PRISMARINE, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.PRISMARINE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.PRISMARINE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.PRISMARINE_WALL, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.PRISMARINE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.PRISMARINE_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.PRISMARINE_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.DARK_PRISMARINE, CraftInfo(SkillType.BLACKSMITHY, 28))
        put(Material.DARK_PRISMARINE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.DARK_PRISMARINE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.SEA_LANTERN, CraftInfo(SkillType.BLACKSMITHY, 25))

        // Blacksmithy - Blackstone
        put(Material.POLISHED_BLACKSTONE, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.POLISHED_BLACKSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.POLISHED_BLACKSTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.POLISHED_BLACKSTONE_WALL, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.POLISHED_BLACKSTONE_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.POLISHED_BLACKSTONE_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.POLISHED_BLACKSTONE_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.POLISHED_BLACKSTONE_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.CHISELED_POLISHED_BLACKSTONE, CraftInfo(SkillType.BLACKSMITHY, 28))
        put(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.POLISHED_BLACKSTONE_BUTTON, CraftInfo(SkillType.BLACKSMITHY, 15))

        // Blacksmithy - Iron/Metal items
        put(Material.IRON_BARS, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.IRON_DOOR, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.IRON_TRAPDOOR, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.CAULDRON, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.LIGHTNING_ROD, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.BELL, CraftInfo(SkillType.BLACKSMITHY, 35))
        put(Material.BREWING_STAND, CraftInfo(SkillType.BLACKSMITHY, 30))

        // Blacksmithy - Copper items
        put(Material.CUT_COPPER, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.CUT_COPPER_SLAB, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.CUT_COPPER_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.COPPER_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.COPPER_GRATE, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.COPPER_BULB, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.COPPER_DOOR, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.COPPER_TRAPDOOR, CraftInfo(SkillType.BLACKSMITHY, 22))
        put(Material.CHISELED_COPPER, CraftInfo(SkillType.BLACKSMITHY, 22))

        // Blacksmithy - Waxed copper (same difficulty as unwaxed)
        put(Material.WAXED_CUT_COPPER, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.WAXED_CUT_COPPER_SLAB, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.WAXED_CUT_COPPER_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.WAXED_COPPER_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.WAXED_COPPER_GRATE, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.WAXED_COPPER_BULB, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.WAXED_CHISELED_COPPER, CraftInfo(SkillType.BLACKSMITHY, 22))

        // Blacksmithy - Sandstone variants
        put(Material.SANDSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.SANDSTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.SANDSTONE_WALL, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.CHISELED_SANDSTONE, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.CUT_SANDSTONE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.CUT_SANDSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.SMOOTH_SANDSTONE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.SMOOTH_SANDSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.SMOOTH_SANDSTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.RED_SANDSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.RED_SANDSTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.RED_SANDSTONE_WALL, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.CHISELED_RED_SANDSTONE, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.CUT_RED_SANDSTONE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.CUT_RED_SANDSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.SMOOTH_RED_SANDSTONE, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.SMOOTH_RED_SANDSTONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.SMOOTH_RED_SANDSTONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 8))

        // Blacksmithy - Purpur
        put(Material.PURPUR_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 28))
        put(Material.PURPUR_PILLAR, CraftInfo(SkillType.BLACKSMITHY, 28))
        put(Material.PURPUR_SLAB, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.PURPUR_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 25))
        put(Material.END_ROD, CraftInfo(SkillType.BLACKSMITHY, 25))

        // Blacksmithy - Tuff variants
        put(Material.TUFF_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.TUFF_BRICK_SLAB, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.TUFF_BRICK_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.TUFF_BRICK_WALL, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.POLISHED_TUFF, CraftInfo(SkillType.BLACKSMITHY, 12))
        put(Material.POLISHED_TUFF_SLAB, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.POLISHED_TUFF_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.POLISHED_TUFF_WALL, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.CHISELED_TUFF, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.CHISELED_TUFF_BRICKS, CraftInfo(SkillType.BLACKSMITHY, 20))

        // Craftsmanship - Paper/Book items
        put(Material.PAPER, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BOOK, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.WRITABLE_BOOK, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.MAP, CraftInfo(SkillType.CRAFTSMANSHIP, 15))

        // Craftsmanship - Miscellaneous
        put(Material.TORCH, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.SOUL_TORCH, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.LEAD, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.NAME_TAG, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.SCAFFOLDING, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.BUNDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.CAMPFIRE, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.SOUL_CAMPFIRE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.BEEHIVE, CraftInfo(SkillType.CRAFTSMANSHIP, 18))
        put(Material.BRUSH, CraftInfo(SkillType.CRAFTSMANSHIP, 15))

        // Craftsmanship - Wool (all colors)
        put(Material.WHITE_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.ORANGE_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.MAGENTA_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.LIGHT_BLUE_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.YELLOW_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.LIME_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.PINK_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.GRAY_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.LIGHT_GRAY_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.CYAN_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.PURPLE_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BLUE_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BROWN_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.GREEN_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.RED_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.BLACK_WOOL, CraftInfo(SkillType.CRAFTSMANSHIP, 5))

        // Craftsmanship - Colored candles (all colors)
        put(Material.WHITE_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.ORANGE_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.MAGENTA_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.LIGHT_BLUE_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.YELLOW_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.LIME_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.PINK_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.GRAY_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.LIGHT_GRAY_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.CYAN_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.PURPLE_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.BLUE_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.BROWN_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.GREEN_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.RED_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.BLACK_CANDLE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))

        // Craftsmanship - Shulker boxes (all colors + default)
        put(Material.SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.WHITE_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.ORANGE_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.MAGENTA_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.LIGHT_BLUE_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.YELLOW_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.LIME_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.PINK_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.GRAY_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.LIGHT_GRAY_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.CYAN_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.PURPLE_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.BLUE_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.BROWN_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.GREEN_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.RED_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))
        put(Material.BLACK_SHULKER_BOX, CraftInfo(SkillType.CRAFTSMANSHIP, 30))

        // Craftsmanship - Stained glass blocks (all colors)
        put(Material.WHITE_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.ORANGE_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.MAGENTA_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIGHT_BLUE_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.YELLOW_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIME_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.PINK_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GRAY_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.LIGHT_GRAY_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.CYAN_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.PURPLE_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BLUE_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BROWN_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.GREEN_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.RED_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.BLACK_STAINED_GLASS, CraftInfo(SkillType.CRAFTSMANSHIP, 10))

        // Craftsmanship - Colored terracotta (all colors)
        put(Material.WHITE_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.ORANGE_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.MAGENTA_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.LIGHT_BLUE_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.YELLOW_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.LIME_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.PINK_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.GRAY_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.LIGHT_GRAY_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.CYAN_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.PURPLE_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BLUE_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BROWN_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.GREEN_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.RED_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.BLACK_TERRACOTTA, CraftInfo(SkillType.CRAFTSMANSHIP, 12))

        // Blacksmithy - High-tier utility blocks
        put(Material.ENDER_CHEST, CraftInfo(SkillType.BLACKSMITHY, 50))
        put(Material.ENCHANTING_TABLE, CraftInfo(SkillType.BLACKSMITHY, 55))
        put(Material.BEACON, CraftInfo(SkillType.BLACKSMITHY, 80))
        put(Material.RESPAWN_ANCHOR, CraftInfo(SkillType.BLACKSMITHY, 60))
        put(Material.LODESTONE, CraftInfo(SkillType.BLACKSMITHY, 55))
        put(Material.CONDUIT, CraftInfo(SkillType.BLACKSMITHY, 65))

        // Craftsmanship - Compressed blocks
        put(Material.SLIME_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.HONEY_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.HONEYCOMB_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.HAY_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.DRIED_KELP_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.BONE_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.MELON, CraftInfo(SkillType.CRAFTSMANSHIP, 10))
        put(Material.SNOW_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 5))
        put(Material.MAGMA_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.PACKED_ICE, CraftInfo(SkillType.CRAFTSMANSHIP, 15))
        put(Material.BLUE_ICE, CraftInfo(SkillType.CRAFTSMANSHIP, 20))
        put(Material.MOSS_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.NETHER_WART_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 12))
        put(Material.WARPED_WART_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 12))

        // Craftsmanship - Pumpkin items
        put(Material.CARVED_PUMPKIN, CraftInfo(SkillType.CRAFTSMANSHIP, 8))
        put(Material.JACK_O_LANTERN, CraftInfo(SkillType.CRAFTSMANSHIP, 10))

        // Alchemy - Ingredients (for skill gain when crafting reagents)
        put(Material.FERMENTED_SPIDER_EYE, CraftInfo(SkillType.ALCHEMY, 25))
        put(Material.GLISTERING_MELON_SLICE, CraftInfo(SkillType.ALCHEMY, 20))
        put(Material.MAGMA_CREAM, CraftInfo(SkillType.ALCHEMY, 25))
        put(Material.BLAZE_POWDER, CraftInfo(SkillType.ALCHEMY, 20))
        put(Material.FIRE_CHARGE, CraftInfo(SkillType.ALCHEMY, 22))
        put(Material.ENDER_EYE, CraftInfo(SkillType.ALCHEMY, 35))

        // Cooking - Food items
        put(Material.SUGAR, CraftInfo(SkillType.COOKING, 5))
        put(Material.GOLDEN_APPLE, CraftInfo(SkillType.COOKING, 60))
        put(Material.PUMPKIN_PIE, CraftInfo(SkillType.COOKING, 20))

        // Craftsmanship - Firework and misc
        put(Material.FIREWORK_STAR, CraftInfo(SkillType.CRAFTSMANSHIP, 25))
        put(Material.END_CRYSTAL, CraftInfo(SkillType.CRAFTSMANSHIP, 50))
        put(Material.RECOVERY_COMPASS, CraftInfo(SkillType.CRAFTSMANSHIP, 45))

        // Blacksmithy - Storage blocks (metal compression)
        put(Material.IRON_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 20))
        put(Material.GOLD_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.DIAMOND_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 35))
        put(Material.EMERALD_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 40))
        put(Material.LAPIS_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.REDSTONE_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.COAL_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 10))
        put(Material.NETHERITE_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 55))
        put(Material.RAW_IRON_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.RAW_GOLD_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 18))
        put(Material.RAW_COPPER_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 15))
        put(Material.AMETHYST_BLOCK, CraftInfo(SkillType.BLACKSMITHY, 20))

        // Blacksmithy - Stone pressure plates and buttons
        put(Material.STONE_PRESSURE_PLATE, CraftInfo(SkillType.BLACKSMITHY, 8))
        put(Material.STONE_BUTTON, CraftInfo(SkillType.BLACKSMITHY, 5))

        // Craftsmanship - Dyes (craftable ones)
        put(Material.BLACK_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BLUE_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BROWN_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.CYAN_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.GRAY_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.GREEN_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.LIGHT_BLUE_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.LIGHT_GRAY_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.LIME_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.MAGENTA_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.ORANGE_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.PINK_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.PURPLE_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.RED_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.WHITE_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.YELLOW_DYE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))

        // Craftsmanship - Planks (all wood types)
        put(Material.OAK_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.SPRUCE_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.BIRCH_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.JUNGLE_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.ACACIA_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.DARK_OAK_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.CRIMSON_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.WARPED_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.MANGROVE_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.CHERRY_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.BAMBOO_PLANKS, CraftInfo(SkillType.CRAFTSMANSHIP, 1))
        put(Material.BAMBOO_MOSAIC, CraftInfo(SkillType.CRAFTSMANSHIP, 3))

        // Craftsmanship - Wood blocks (stripped/etc)
        put(Material.STRIPPED_OAK_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_SPRUCE_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_BIRCH_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_JUNGLE_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_ACACIA_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_DARK_OAK_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_MANGROVE_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_CHERRY_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.STRIPPED_CRIMSON_HYPHAE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.STRIPPED_WARPED_HYPHAE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.STRIPPED_BAMBOO_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.OAK_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.SPRUCE_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.BIRCH_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.JUNGLE_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.ACACIA_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.DARK_OAK_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.MANGROVE_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CHERRY_WOOD, CraftInfo(SkillType.CRAFTSMANSHIP, 2))
        put(Material.CRIMSON_HYPHAE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.WARPED_HYPHAE, CraftInfo(SkillType.CRAFTSMANSHIP, 3))
        put(Material.BAMBOO_BLOCK, CraftInfo(SkillType.CRAFTSMANSHIP, 2))

        // Blacksmithy - Andesite/Diorite/Granite base blocks
        put(Material.ANDESITE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.ANDESITE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.ANDESITE_WALL, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.DIORITE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.DIORITE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.DIORITE_WALL, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.GRANITE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.GRANITE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.GRANITE_WALL, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.STONE_SLAB, CraftInfo(SkillType.BLACKSMITHY, 6))
        put(Material.STONE_STAIRS, CraftInfo(SkillType.BLACKSMITHY, 6))
    }

    fun getCraftInfo(material: Material): CraftInfo? = craftInfoMap[material]

    fun getSkillForMaterial(material: Material): SkillType? = craftInfoMap[material]?.skill

    fun getDifficulty(material: Material): Int = craftInfoMap[material]?.difficulty ?: 20
}
